# Generated by Django 2.2.4 on 2020-11-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
